services:
  db:
    container_name: db
    image: postgres:15.1-alpine
    restart: always
    networks:
      - app
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
    volumes:
      - ./pgdata/:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks: 
      - app
    restart: unless-stopped
    volumes:
      - ./src/:/app/src/
    depends_on:
      - db
    ports:
      - $API_PORT:$API_PORT
    environment:
      - API_PORT=$API_PORT
      - API_HOST=$API_HOST
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DATABASE
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_HOST=db
networks:
  app: 
    driver: bridge