FROM node:18-alpine as dev
WORKDIR /app
COPY package*.json ./
COPY tsconfig*.json ./
COPY ./src/mail/templates/*.tmp.hbs ./dist/mail/templates/
COPY .env ./
RUN npm install
COPY ./src ./src
EXPOSE ${API_PORT}
VOLUME ./src ./src
CMD ["npm","run", "start:dev"]
