FROM node:18-alpine AS prod
WORKDIR /app
COPY package*.json tsconfig.json  ./
COPY ./src/mail/templates/*.tmp.hbs ./dist/mail/templates/
COPY .env ./
RUN npm install
COPY ./src ./src
VOLUME ./src/ ./src
RUN npm run build

FROM node:18-alpine
WORKDIR /app
COPY --from=prod /app ./
EXPOSE ${API_PORT}
CMD ["npm", "run", "start:prod"]